---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app-image
          envFrom:
            - configMapRef:
                name: my-app-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  DATABASE_HOST: my-database
  DATABASE_PORT: "5432"
  DATABASE_USER: myuser
  DATABASE_PASSWORD: mysecretpassword 

# A ConfigMap is a Kubernetes object used to store configuration data in key-value pairs. It allows you to decouple your application configurations from your application code, making it easier to manage and update configurations without redeploying your application.